# Generated by Django 4.2.30 on 2026-05-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(choices=[(8, '8 hours'), (16, '16 hours'), (24, '24 hours'), (32, '32 hours'), (40, '40 hours'), (48, '48 hours'), (56, '56 hours'), (64, '64 hours')], unique=True, verbose_name='Hours')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price (USD)')),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Package')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hourly Package',
                'verbose_name_plural': 'Hourly Packages',
                'ordering': ['hours'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='English Name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Arabic Name')),
                ('slug', models.SlugField(unique=True)),
                ('icon_svg', models.TextField(blank=True, verbose_name='SVG Icon')),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('is_test_prep', models.BooleanField(default=False, verbose_name='Test Prep Subject')),
                ('test_prep_badge', models.CharField(blank=True, help_text='e.g. SAT, IELTS, TOEFL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('color_accent', models.CharField(default='#00c9c9', help_text='Hex color for card accent', max_length=7)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('hours_at_purchase', models.PositiveSmallIntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=8)),
                ('referral_processed', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='courses.hourlypackage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
