# Generated by Django 4.2.30 on 2026-05-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlypackage',
            name='price_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price (AED)'),
        ),
    ]
