# Generated by Django 6.0.6 on 2026-06-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_hourlypackage_price_aed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color_accent',
            field=models.CharField(default='#008b8b', help_text='Hex color for card accent', max_length=7),
        ),
    ]
