# Generated by Django 6.0.6 on 2026-06-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_studentenrollment_teachersubjectrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('requested', 'Requested')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
    ]
